spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/test
      

mybatis:
  type-aliases-package: com.cusonar.ib.domain
  mapper-locations:
  - mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: varchar
    
#logging:
#  level:
#    com.cusonar.ib.usage.UsageInfoMapper: debug
    
ib:
  pre.loader.data.path: data/2019년하반기_서버개발자_데이터.csv
  jwt.secret: kakaopay